name: Tag release 

# Controls when the action will run. 
on:
  push:
    tags:
      - '*.*'
      
  workflow_dispatch:
env:
  QUAY_REGISTRY: quay.io/gamerefinery
  REPO: internal  
jobs:
  package-build-push:
    runs-on: ubuntu-latest
    container:
      image: quay.io/gamerefinery/github-actions-container:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract release
        id: extract-release
        run: echo "::set-output name=release::$(echo ${{ github.ref }} | cut -d/ -f3)"
      - name: Extract commit SHA
        id: extract_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Release name
        run: echo release ${{steps.extract-release.outputs.release}}
      - name: Commit SHA
        run: echo running on branch ${{steps.extract_sha.outputs.sha_short}}
        
      - name: Login to Quay.io
        run: skopeo login quay.io -u ${{ secrets.QUAY_USERNAME }} -p${{ secrets.QUAY_PASSWORD }}
          
      - name: Tag release image
        run: |
          skopeo copy docker://${{env.QUAY_REGISTRY}}/${{env.REPO}}:release docker://${{env.QUAY_REGISTRY}}/${{env.REPO}}:${{steps.get-release.outputs.release}}