name: Create a release

# Controls when the action will run. 
on:
  push: 
    branches:    
      - 'release/**'
      - 'hotfix/**'

  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract release
        id: extract-release
        run: echo "::set-output name=release::$(echo ${{ github.ref }} | cut -d/ -f4)"
      - name: Extract commit SHA
        id: extract_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Release name
        run: echo release ${{steps.extract-release.outputs.release}}
      - name: Commit SHA
        run: echo running on branch ${{steps.extract_sha.outputs.sha_short}}
      - name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          logout: false  
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            ENVIRONMENT=prod
          push: true
          tags: |
            quay.io/gamerefinery/action-test:${{steps.extract-release.outputs.release}}
            quay.io/gamerefinery/action-test:${{steps.extract_sha.outputs.sha_short}}
            quay.io/gamerefinery/action-test:release