name: Deploy to Staging

# Controls when the action will run. 
on:
  push:
    tags:
      - 'staging'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          logout: false  
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            ENVIRONMENT=stage
          push: true
          tags: |
            quay.io/gamerefinery/action-test:staging