name: Tag release 

# Controls when the action will run. 
on:
  push:
    branches:    
      - 'release/**'
      - 'hotfix/**'
    tags:
      - '*'
      
  workflow_dispatch:
env:
  QUAY_REGISTRY: quay.io/gamerefinery
  REPO: internal  
jobs:
  package-build-push:
    runs-on: ubuntu-latest
    container:
      image: quay.io/gamerefinery/github-actions-container:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract release
        id: extract-release
        run: echo "::set-output name=release::$(echo ${{ github.ref }} | cut -d/ -f4)"
      - name: Extract commit SHA
        id: extract_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Release name
        run: echo release ${{steps.extract-release.outputs.release}}
      - name: Commit SHA
        run: echo running on branch ${{steps.extract_sha.outputs.sha_short}}
      - name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          logout: false  
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
          
      - name: Tag release image
        run: |
          skopeo copy docker://${{env.QUAY_REGISTRY}}/${{env.REPO}}:${{ steps.vars.outputs.sha_short }} docker://${{env.QUAY_REGISTRY}}/${{env.REPO}}:${{steps.get-release.outputs.release}}