name: Deploy to Dev

# Controls when the action will run. 
on:
  push:
    tags:
      - 'dev'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract commit SHA
        id: extract_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Branch name
        run: echo running on branch ${{steps.extract_branch.outputs.branch}}
      - name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          logout: false  
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            ENVIRONMENT=dev
          push: true
          tags: |
            quay.io/gamerefinery/action-test:dev
            quay.io/gamerefinery/action-test:${{steps.extract_sha.outputs.sha_short}}
            quay.io/gamerefinery/action-test:${{steps.extract_branch.outputs.branch}}