name: Deploy hotfix

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #release:
  #  types: [published]
  push:
    branches: [ hotfix/*]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - id: get-branch
        run: echo "::set-output name=branch::$(echo ${{ github.ref }} | cut -d/ -f3)"
      - name: Branch name
        run: echo running on branch ${{steps.get-branch.outputs.branch}}
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          logout: false  
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            ENVIRONMENT=prod
          push: true
          tags: |
            quay.io/gamerefinery/action-test:${{steps.get-branch.outputs.branch}}